#!/usr/bin/env ruby

solutions = File.open("solutions.txt") { |f|
  f.read.split("\n").map { |s| s.split.last }
}

if ARGF.argv.count == 1
  problem = ARGF.argv.first

  if File.exists?("solutions/problem#{problem}.rb")
    command = "ruby solutions/problem#{problem}.rb"
  elsif File.exists?("solutions/problem#{problem}.py")
    command = "python solutions/problem#{problem}.py"
  else
    puts "No solution implementation found"
    exit
  end

  start = Time.now
  solution = `#{command}`.strip
  finish = Time.now

  puts "Took #{finish - start} seconds"
else
  problem, solution = ARGF.argv
end

if solution == solutions[problem.to_i - 1]
  puts "Correct, the answer is #{solution}"
else
  puts "Incorrect, the answer is not #{solution}"
end
