#!/usr/bin/env ruby

solutions = File.open("solutions.txt") { |f|
  f.read.split("\n").map { |s| s.split.last }
}

if ARGF.argv.count == 1
  problem = ARGF.argv.first

  file_name = "solutions/problem#{problem}"
  if File.exists?("#{file_name}.rb")
    command = "ruby #{file_name}.rb"
  elsif File.exists?("#{file_name}.py")
    command = "python #{file_name}.py]"
  elsif File.exists?("#{file_name}.cpp")
    `clang++ -g -Wall -std=c++11 -stdlib=libc++ #{file_name}.cpp -o solutions/bin/#{problem}`
    command = "solutions/bin/#{problem}"
  else
    puts "No solution implementation found"
    exit
  end

  start = Time.now
  solution = `#{command}`.strip
  finish = Time.now

  puts "Took #{finish - start} seconds"
else
  problem, solution = ARGF.argv
end

if solution == solutions[problem.to_i - 1]
  puts "Correct, the answer is #{solution}"
else
  puts "Incorrect, the answer is not #{solution}"
end
